#
# (c) 2024 Helixiome, all rights reserved.
# (c) 2024 中基科生物保留所有权利
#
# Author(s):
# Andrew P. Hutchins
#

import utils
from . import html_data

def html(
    lang:str,
    patient_id:str,
    search_term:str,
    patient_data:dict,
    main_table:str,
    no_reccomendation_table:str,
    summary_table:str,
    ):

    # TODO: check patient data
    # TODO: check valid language
    if lang == 'EN':
        if not no_reccomendation_table: no_reccomendation_table = '<td>None</td><td>None</td>'
        return html_en(patient_id=patient_id, search_term=search_term, patient_data=patient_data,
            main_table=main_table, no_reccomendation_table=no_reccomendation_table, summary_table=summary_table)
    elif lang == 'CN':
        if not no_reccomendation_table: no_reccomendation_table = '<td>无</td><td>无</td>'
        return html_cn(patient_id=patient_id, search_term=search_term, patient_data=patient_data,
            main_table=main_table, no_reccomendation_table=no_reccomendation_table, summary_table=summary_table)


def html_en(
    patient_id:str,
    search_term:str,
    patient_data:dict,
    main_table:str,
    no_reccomendation_table:str,
    summary_table:str,
    ):
    # English version;

    html = f'''

<!DOCTYPE html>
<html>
<head>
<style>
{html_data.style_sheet}
</style>
</head>
<body>

<div style="display: flex; justify-content: space-between;">
  <img src='{html_data.helix_logo}'>
  <h1 style="text-align: right;">Pharmacogenomics report</h1>
</div>

<h1>Patient data</h2>

<table style="width:70%">
    <tr>
        <td style="background-color: var(--tab-grey-bg);">Patient ID</td>
        <td colspan="5">{patient_id}</td>
    </tr>
    <tr>
        <td style="background-color: var(--tab-grey-bg);">Name</td>
        <td>{utils.obfuscate_name(patient_data['name'])}</td>
        <td style="background-color: var(--tab-grey-bg);">Age</td>
        <td>{patient_data['age']}</td>
        <td style="background-color: var(--tab-grey-bg);">Sex</td>
        <td>{patient_data['sex']}</td>
    </tr>
    <tr>
        <td style="background-color: var(--tab-grey-bg);">Search Term<</td>
        <td colspan="5">{search_term}</td>
    </tr>
</table>

<h2>Guidance</h2>

<p>The following report was generated based upon sequencing data for the whole genome.
The report provides guidance on the efficacy of particular drugs, used in the treatment of
{search_term}. The table lists drugs, the specific SNP and genotype of the patient, and
provides potential guidance for treatment. The data here constitutes the best advice and
care should be taken in interpreting these results.
and best clinical practice should be followed.</p>

<h2>Summary Table</h2>

<table style="width:100%">
    <tr>
        <td>Drug</td>
        <td>Genes</td>
        <td>Efficacy</td>
        <td>Metabolism</td>
        <td>Risk</td>
        <td>Toxicity</td>
    </tr>
    {summary_table}
</table>

<h2>Drug guidance summary</h2>

<p>Note the evidence level, which indicates the evidence supporting the genetic-drug
association. Levels 1A, 1B are well supported, 2A, 2B are likely, level 3 has some supporting
evidence of an association.</p>

<table>
    <tr>
        <td>Drug</td>
        <td>SNP Genotype</td>
        <td>Evidence Level</td>
        <td>Guidance</td>
    </tr>
    {main_table}
</table>

<br>No guidance available, treat normally.
<table style="width:60%">
    <tr>
        <td>Drug</td>
        <td>Guidance</td>
    </tr>
    {no_reccomendation_table}
</table>

<h2>Post script</h2>
<p>Generated by Helixiome.</p>

</body>
    '''
    return html

#############################

def html_cn(
    patient_id:str,
    search_term:str,
    patient_data:dict,
    main_table:str,
    no_reccomendation_table:str,
    summary_table:str,
    ):
    # Chinese version;

    html = f'''

<!DOCTYPE html>
<html>
<head>
<style>
{html_data.style_sheet}
</style>
</head>
<body>

<div style="display: flex; justify-content: space-between;">
  <img src='{html_data.helix_logo}'>
  <h1 style="text-align: right;">药物基因组学报告</h1>
</div>

<hr>

<h2>患者数据</h2>

<table style="width:70%">
    <tr>
        <td style="background-color: var(--tab-grey-bg);">患者 ID</td>
        <td colspan="5">{patient_id}</td>
    </tr>
    <tr>
        <td style="background-color: var(--tab-grey-bg);">姓名</td>
        <td>{utils.obfuscate_name(patient_data['name'])}</td>
        <td style="background-color: var(--tab-grey-bg);">年龄</td>
        <td>{patient_data['age']}</td>
        <td style="background-color: var(--tab-grey-bg);">性别</td>
        <td>{patient_data['sex']}</td>
    </tr>
    <tr>
        <td style="background-color: var(--tab-grey-bg);">疾病</td>
        <td colspan="5">{search_term}</td>
    </tr>
</table>

<h2>声明</h2>

<p>以下报告是根据整个基因组的测序数据生成的。
该报告为用于治疗的特定药物的疗效提供了指导
{search_term}。该表列出了药物、患者的特定SNP和基因型，以及
为治疗提供了潜在的指导。此处的数据构成了最佳建议和
在解释这些结果时应小心谨慎。
并应遵循临床实践。</p>

<h2>汇总表</h2>

<table style="width:100%">
    <tr>
        <th>药物</th>
        <th>基因</th>
        <th>疗效</th>
        <th>代谢</th>
        <th>风险</th>
        <th>毒性</th>
        <th>剂量</th>
        <th>常规用药</th>
    </tr>
    {summary_table}
</table>

<h3>精准用药汇总</h3>
<table>
    <tr>
        <th>药物</th>
        <th>基因</th>
        <th>单核苷酸多态性 (SNP) 基因型</th>
        <th>效应</th>
        <th>指南建议</th>
        <th>证据等级</th>
    </tr>
    {main_table}
</table>

<h3>常规用药</h3>
<table style="width:60%">
    <tr>
        <th>药物</th>
        <th>用药建议</th>
    </tr>
    {no_reccomendation_table}
</table>

<h2>注意</h2>

<p>注意：证据水平等级，表明支持遗传药物的证据 协会，1A、1B级表示得到很好的支持，2A、2B级可能得到支持，3级有一些支持关联的证据。</p>


<hr>

<h6 style='text-align:right'>中基科生物</h6>


</body>
</html>
    '''
    return html


